### ISSUE TITLE
DXVK 1.10 and vkd3d-proton 2.6 released!

### ISSUE THREAD

**Issue by ghost** [lutris/dxvk#11]
https://github.com/doitsujin/dxvk/releases/tag/v1.10

Important game fixes and many other fixes for D3D11 and D3D9

And as for D3D12, there was vkd3d-proton 2.6 release:
https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.6

**Comment by totof3110** [comment]
DXVK is now at [2.0](https://github.com/doitsujin/dxvk/releases/tag/v2.0) and VKD3D at [2.8](https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.8). I know it's possible to manually install those runtimes but it would be great if Lutris' default settings could catch up. :)
