### ISSUE TITLE
DXVK release 1.8?

### ISSUE THREAD

**Issue by ghost** [lutris/dxvk#5]
https://github.com/doitsujin/dxvk/releases/tag/v1.8

Any plans to release Lutris version?

**Comment by jntesteves** [comment]
Was released yesterday https://github.com/lutris/dxvk/releases/tag/v1.8.1L

@tannisroot The release description was copied from previous version and not updated, it doesn't point to the right commits.

**Comment by tannisroot** [comment]
sorry fixed that
