### ISSUE TITLE
dxvk v1.9.4 released, please release v1.9.4L

### ISSUE THREAD

**Issue by lizthegrey** [lutris/dxvk#8]
https://github.com/doitsujin/dxvk/releases/tag/v1.9.3

**Comment by ghost** [comment]
Along with DXVK (which is 1.9.4 by now), also Wine builds not yet up to 7.x series, dxvk-nvapi is outdated (version 0.5.2 by now), lutris winetricks outdated (git updates)

Only that seem to be on latest version is vkd3d (2.5 release from October 2021, not surprised if update soon)

**Comment by lizthegrey** [comment]
Appears fixed now.
